import Logo from "../Image/DocMeds-favicon.png";
import HomeBg from "../Image/DocMed-home-bg.jpg";
import Card1 from "../Image/Card/card-1.webp"
import Card2 from "../Image/Card/card-2.webp"
import Card3 from "../Image/Card/card-3.webp"
import Card4 from "../Image/Card/card-4.webp"
import Card5 from "../Image/Card/card-5.webp"
import Card6 from "../Image/Card-2/img-1.jpg"
import Card7 from "../Image/Card-2/img-2.webp"
import Card8 from "../Image/Card-2/img-3.jpg"
import Card9 from "../Image/Card-2/img-4.jpg"
import Card10 from "../Image/Card-2/img-5.jpg"
import Card11 from "../Image/Card-2/img-6.jpg"
import Card12 from "../Image/Card-2/img-7.webp"
import Card13 from "../Image/Card-3/img-1.webp"
import Card14 from "../Image/Card-3/img-2.webp"
import Card15 from "../Image/Card-3/img-3.webp"
import Card16 from "../Image/Card-3/img-4.webp"
import Card17 from "../Image/Card-3/img-5.webp"
import Card18 from "../Image/Card-3/img-6.webp"
import Card19 from "../Image/Card-3/img-6.webp"
import Card20 from "../Image/Category-img/categoryImg-1.webp"
import Card21 from "../Image/Category-img/categoryImg-2.webp"
import Card22 from "../Image/Category-img/categoryImg-3.webp"
import Card23 from "../Image/Category-img/categoryImg-4.webp"
import Card24 from "../Image/Category-img/categoryImg-5.webp"
import Card25 from "../Image/Category-img/categoryImg-6.webp"
import Card26 from "../Image/Category-img/categoryImg-7.webp"
import Card27 from "../Image/Category-img/categoryImg-8.webp"
import Card28 from "../Image/Category-img/categoryImg-9.webp"
import Card29 from "../Image/Category-img/categoryImg-10.webp"
import Card30 from "../Image/Category-img/categoryImg-11.webp"
import Card31 from "../Image/Category-img/categoryImg-12.webp"
import Card32 from "../Image/condition-card/healthImg-1.webp"
import Card33 from "../Image/condition-card/healthImg-2.webp"
import Card34 from "../Image/condition-card/healthImg-3.webp"
import Card35 from "../Image/condition-card/healthImg-4.webp"
import Card36 from "../Image/condition-card/healthImg-5.webp"
import Card37 from "../Image/condition-card/healthImg-6.webp"
import Card38 from "../Image/condition-card/healthImg-7.webp"
import Card39 from "../Image/condition-card/healthImg-8.webp"
import Card40 from "../Image/condition-card/healthImg-9.webp"

export{Logo,Card1,HomeBg,Card2,Card3,Card6,Card4,Card5,Card7,Card8,Card9,Card10,Card11,Card12,Card13,Card14,Card15,Card16,Card17,Card18,
    Card19,Card20,Card21,Card22,Card23,Card24,Card25,Card26,Card27,Card28,Card29,Card30,Card31,Card32,Card33,Card34,Card35,Card36,Card37,Card38,Card39,Card40
}